# Generated by Django 3.2.4 on 2021-06-15 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('strategies', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CoveredCall',
            fields=[
                ('id', models.ForeignKey(default=models.BigAutoField(primary_key=True), on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='optionsPF.portfolio')),
                ('strike', models.PositiveIntegerField()),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateTimeField()),
                ('num_contracts', models.PositiveIntegerField()),
                ('ticker', models.CharField(max_length=5)),
                ('strategy_name', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='optionsPF.portfolio')),
            ],
        ),
    ]
