# Generated by Django 3.2.4 on 2021-06-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionsPF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButterflySpread',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('strike', models.PositiveIntegerField()),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('num_contracts', models.PositiveIntegerField()),
                ('ticker', models.CharField(max_length=5)),
                ('strategy_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Butterfly',
        ),
    ]
