# Generated by Django 3.2.4 on 2021-06-24 23:51
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionsPF', '0010_auto_20210624_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='id',
            field=models.BigAutoField(auto_created=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
