# Generated by Django 3.2.4 on 2021-06-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionsPF', '0011_portfolio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
