# Generated by Django 3.2.4 on 2021-06-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionsPF', '0013_auto_20210626_0636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='butterflyspread',
            old_name='strike',
            new_name='lower_bound_strike',
        ),
        migrations.AddField(
            model_name='butterflyspread',
            name='lower_contract_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='butterflyspread',
            name='midpoint_contract_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='butterflyspread',
            name='midpoint_strike',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='butterflyspread',
            name='upper_bound_strike',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='butterflyspread',
            name='upper_contract_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
