# Generated by Django 3.2.4 on 2021-06-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optionsPF', '0014_auto_20210626_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='butterflyspread',
            old_name='contract_price',
            new_name='strategy_price',
        ),
    ]
