# Generated by Django 3.2.4 on 2021-06-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionsPF', '0016_auto_20210627_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='butterflyspread',
            name='collapsible_tag',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
