# Generated by Django 3.2.4 on 2021-06-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionsPF', '0018_alter_butterflyspread_collapsible_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butterflyspread',
            name='strategy_name',
            field=models.CharField(max_length=40),
        ),
    ]
