# Generated by Django 3.2.4 on 2021-07-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionsPF', '0020_auto_20210627_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='butterflyspread',
            name='current_contract_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='butterflyspread',
            name='current_high_strike_contract_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='butterflyspread',
            name='current_low_strike_contract_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='butterflyspread',
            name='current_mid_strike_contract_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
