# Generated by Django 3.2.4 on 2021-07-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optionsPF', '0021_auto_20210702_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='butterflyspread',
            old_name='current_contract_price',
            new_name='current_strategy_price',
        ),
    ]
